Make it easy to clear the value of a property
BHoM/BHoM_UI pull request #334
Opened 2020-11-12 07:02 UTC by adecler

### NOTE: Depends on 
https://github.com/BHoM/BHoM_Engine/pull/2142

   
### Issues addressed by this PR

Closes #141 

With this PR, it is now easy to clear the value of a property by leaving the `value` input empty. Here's how it behaves:
- Value types like primitives and enums are set to their default value (value types cannot be null)
- Any IEnumerable is set to an empty version of that type.
- Strings are set to an empty string (it could be set to null but I think this is the only case where it makes more sense not to)
- All other objects are set to null.

Looks like a lot of cases listed like that but I found it pretty intuitive when actually used. Let me know if you disagree.

### Test files
https://burohappold.sharepoint.com/:u:/r/sites/BHoM/02_Current/12_Scripts/01_Test%20Scripts/BHoM_UI/BHoM_UI-Issue141-SetPropertyDefault.gh?csf=1&web=1&e=i1YFbh

### Additional comments
Note that the issue @kThorsager was complaining about related to the list type disappearing when copying the component has been solved during the refactoring of the UI.

2020-11-12 12:30 UTC, pawelbaran requested changes
I went through this PR as well as https://github.com/BHoM/BHoM_Engine/pull/2142 - please consider this review as combined for both.

I see two points I am not sure about. Firstly, the enums get reset to their first value (value equal to 0 I guess), which might be confusing as sometimes the desired default might not sit under 0. Not sure if it would not be possible, but maybe the properties could be reset not to zero/null, but to their default values instead (and zero/null if there is no default value)?

Second issue is purely technical, I get an error after opening the file:
![image](https://user-images.githubusercontent.com/26874773/98940312-1600d580-24eb-11eb-9d53-dda354c43363.png)

2020-11-13 03:07 UTC, adecler commented
>I see two points I am not sure about. Firstly, the enums get reset to their first value (value equal to 0 I guess), which might be confusing as sometimes the desired default might not sit under 0. Not sure if it would not be possible, but maybe the properties could be reset not to zero/null, but to their default values instead (and zero/null if there is no default value)?

That would mean a different behaviour for enums than for all other types as this always sets to the equivalent of null, not to the initial value of the property. Keep in mind that this is purely to provide a behaviour in every case that is consistent. If we want to reset to the initial value of the property, we have to do it for every type. It then requires knowledge of the what those values are as they are not always null. It also means that, if the initial value is not null, there would actually be no way of setting it to null even with this component. I also don't expect the user to leave the `value` input empty when it makes no sense to do so (and if they do so, I have a ready made answer for them 😉 ).

2020-11-13 03:18 UTC, adecler commented
> Second issue is purely technical, I get an error after opening the file:

I forgot to save it with the `value` input saved as a list. Changing that, saving, and reopening the file works perfectly fine for me. Can you confirm it is the case for you too ?

2020-11-13 10:27 UTC, pawelbaran approved these changes
Following today's discussion happy with the changes. However, I just thought of a neat improvement: would it be possible to set the property value to null regardless its type (item/list/tree), so that the user would not need to change input type through the UI (the error mentioned by me [here](https://github.com/BHoM/BHoM_UI/pull/334#pullrequestreview-529039523) could be avoided)?

2020-11-14 02:41 UTC, adecler commented
/azp run BHoM_UI.CheckInstaller

2020-11-17 01:43 UTC, merged