BHoM_UI: Detect startup using UTC time instead of local time
BHoM/BHoM_UI pull request #336
Opened 2020-11-17 04:26 UTC by adecler

### NOTE: Depends on 
https://github.com/BHoM/BHoM/pull/1092

   
### Issues addressed by this PR

Closes #335

It seems that some events recorded in Revit are using UTC time instead of local time despite using `DateTime.Now` and not `DateTime.UtcNow`. So detecting startup events can only be done reliably using UTC time everywhere. 

It is important to note, that I keep using local time for the `since` input of `GetEvents` because this is something provided by the user. 

### Test files

### Changelog

### Additional comments

2020-11-17 09:05 UTC, FraserGreenroyd approved these changes
Code LGTM in line with the oM addition

2020-11-17 09:10 UTC, FraserGreenroyd commented
@BHoMBot check installer

2020-11-17 10:40 UTC, pawelbaran requested changes
The original issue still persists. Even worse, in point 3. of it (pulling of the element 1394404), the startup warnings finally appear, but not in the startup section:

![image](https://user-images.githubusercontent.com/26874773/99379490-086f9500-28c9-11eb-8e53-1dc50ee9dc6c.png)

@FraserGreenroyd could you please try opening an empty GH doc on this branch and check if `GetEvents` logs startup messages under startup output? That is the 1st thing that already goes wrong on my build (see point 1. in https://github.com/BHoM/BHoM_UI/issues/335).

2020-11-17 10:42 UTC, FraserGreenroyd commented
> @FraserGreenroyd could you please try opening an empty GH doc on this branch and check if `GetEvents` logs startup messages under startup output? That is the 1st thing that already goes wrong on my build (see point 1. in #335).

Interesting, I'll take another look 😕

2020-11-19 08:10 UTC, adecler commented
@pawelbaran , everything actually works exactly as intended.

The issue is that the revit toolkit is not front-loading the BHoM methods so those will only be extracted the first time that method list is needed. In this case, when a call to `RunExtensionMethod` is made:

![image](https://user-images.githubusercontent.com/16853390/99638617-72cb3580-2a81-11eb-8da3-ba77c0c6b425.png)

If you want to test that for yourself, keep in mind you need to attach VS to Revit and not Grasshopper.

2020-11-19 10:41 UTC, pawelbaran commented
@adecler do you mean there is zero startup messages in Grasshopper itself? Opening GH alone, startup warnings are empty:

![image](https://user-images.githubusercontent.com/26874773/99643943-9a080f80-2a4d-11eb-87d2-eb704d0803b3.png)

Coming back to Revit, I have just confirmed your findings, looks like the problem lives inside `RevitListener` - I have transferred the issue to Revit_Toolkit and will resolve it there (I will simply suppress the startup warnings, I am 99.99% sure they will never be relevant by any means).

2020-11-20 02:12 UTC, adecler commented
/azp run BHoM_UI.CheckInstaller

2020-11-20 02:36 UTC, merged