Save file id, file name, and project code in usage log
BHoM/BHoM_UI pull request #370
Opened 2021-02-16 08:33 UTC by adecler

### NOTE: Depends on 
https://github.com/BHoM/BHoM_Engine/pull/2312

   
### Issues addressed by this PR
Provide changes required for fileName and project code to be saved by analytics. Two things were required here:
 - A new component that can be used to associate a script with a specific project
 - new fields in the usage log entries to store file id, file name and project code

A few things to note:
- I use a new type of event that allows to easily have the project code available when processing the log entries. It also serves as a nice way to let the user know that the component did what it was supposed to do.
- I saved file id because the script doesn't have a file name until it is saved. And, at that point, there is no guarantee that the existing components will be ran again. In case there are multiple files opened in a session, it is critical to be able to safely identify the script owning each component.
- I used `projectCode` instead of `projectNumber` (and therefore a string instead of a number) because there is no guarantee that other companies will also use a number.

### Test files
See BHoMAnalytics PR

2021-02-17 05:24 UTC, adecler commented
@BHoMBot check copyright

2021-02-17 05:25 UTC, adecler commented
@BHoMBot check installer

2021-02-17 20:31 UTC, al-fisher requested changes
System working well.
Suggested changes below.

Tested in GH and Excel with other comments given https://github.com/BHoM/Excel_Toolkit/pull/280#pullrequestreview-592432620 and https://github.com/BHoM/Grasshopper_Toolkit/pull/604#pullrequestreview-592600402
Thanks @adecler

2021-02-17 20:41 UTC, al-fisher commented on UI_Engine/Compute/SetProjectCode.cs
> +        public static bool SetProjectCode(string projectCode)
And then actually playing with the tooltips on the canvas - might be worth keeping the verbose _"this script is associated with."_ on both descriptions of method name and input like you had 

```suggestion
        [Description(@"Set the project number or unique project ID this script is associated with.")]
        [Input("projectID", "Project number/unique project ID this script is associated with.")]
        [Output("success", "Returns true if the project ID was correctly registered.")]
        public static bool SetProjectID(string projectID)
```

2021-02-18 03:12 UTC, adecler commented
@BHoMBot check copyright

2021-02-18 03:12 UTC, adecler commented
@BHoMBot check installer

2021-02-18 18:31 UTC, al-fisher approved these changes
Changes look good. Thanks @adecler

2021-02-19 01:41 UTC, merged