Adding link to source for CreateDataCaller
BHoM/BHoM_UI pull request #401
Opened 2021-08-27 08:11 UTC by IsakNaslundBh

### Issues addressed by this PR

Closes #400 

Checking if the dataset contains a SourceLink, and if so, add a link to it in the menu. Really useful to have quick direct access to the source of the data, when available.

Added the functionality for both the Toolstrip and WPF, but was not able to test the WPF as I do not know where it is being called from. Tried in dynamo, but looked as if the menu is only triggered once, when you add the component, and not again when a dataset has been selected. Happy to remove the WPF implementation if we think that is a better way to go.

### Test files

Any of the UK steelsection or EU material datasets should have working links:

![image](https://user-images.githubusercontent.com/22005920/131095067-b2d1df30-167e-4019-ab2f-4e62ae75e1a7.png)

### Changelog

### Additional comments

2021-08-30 02:05 UTC, adecler reviewed
This is working as expected in Grasshopper.

I would however recommend to make some changes before merging. There is no guarantee that other UIs would behave like GH and recreate the menu every time. You already have an example in that with Dynamo. To fix that, you need to also update the menu when the `FileName` is changed. There are a few places you can override to take care of it: 
- `SetItem` method
- `SetComponentDetails` method
- setter of the `SelectedItem` property. 

The `SetComponentDetails` method is probably the simplest place to do it though.

2021-09-10 02:24 UTC, adecler requested changes
A few little things to correct:
- `AddToMenu(ToolStripDropDown menu)` and `AddToMenu(System.Windows.Controls.ContextMenu menu)` are public methods. So they could be called directly without going through `AddToMenu(object menu)` first. So you need to override them. Otherwise, you might have cases where the source link is not added.
- `m_menu` should be named `m_Menu` to follow conventions.

And then a last one that I am happy to overlook in this PR but need to be fixed eventually: It is technically possible for the source link to be outdated if the component was able to Switch between file names. It cannot at the moment but we might want to change that in the future to match the behaviour of the `Type` component. If you don't fix it now, make sure to raise an issue for it.

2021-09-10 08:40 UTC, adecler approved these changes
Now looking good after discussion and commit

2021-09-10 08:50 UTC, IsakNaslundBh commented
@BHoMBot check compliance
@BHoMBot check required

2021-09-16 10:02 UTC, FraserGreenroyd approved these changes
I have tested this with a few datasets which included valid source links, invalid source links, and no source links. At all times, the behaviour was as expected based on the issue described and reviewed against.

This was previously approved for merge prior to the feature freeze implemented for the end of milestone. Although we are now in feature freeze, I am of the opinion that this addition to the UI code increases usability, user experience, and ability to question dataset sources to further increase confidence in datasets.

As such, in my capacity as DevOps lead, I am granting this PR permission to merge during feature freeze for deployment in the 4.3 beta.

2021-09-16 10:02 UTC, merged