Add ability to connect and trigger events when Usage Log is triggered
BHoM/BHoM_UI pull request #425
Opened 2022-08-11 11:42 UTC by FraserGreenroyd

Coming soon

2022-08-19 14:47 UTC, alexissantella requested changes
Requesting changes based on code review.

2022-08-19 14:47 UTC, alexissantella commented on UI_oM/TriggerLogUsageArgs.cs
> +namespace BH.oM.UI
```suggestion
namespace BH.oM.UI, IObject
```

2022-08-19 14:47 UTC, alexissantella commented on UI_oM/TriggerLogUsageArgs.cs
> +        public virtual Guid ComponentID { get; set; }
could we use some defaults?

2022-08-19 15:05 UTC, FraserGreenroyd commented
@BHoMBot check copyright-compliance

2022-08-19 15:32 UTC, FraserGreenroyd commented
@BHoMBot fix copyright headers ref. 7921146293

2022-08-24 18:34 UTC, FraserGreenroyd commented
@BHoMBot check compliance

2022-08-24 18:44 UTC, FraserGreenroyd commented
@BHoMBot check core

2022-08-24 18:50 UTC, travispotterBH approved these changes
https://github.com/BHoM/BHoMAnalytics_Toolkit/pull/35#pullrequestreview-1084342381

2022-08-24 19:32 UTC, FraserGreenroyd commented
@BHoMBot check ready-to-merge

2022-08-24 19:36 UTC, alexissantella approved these changes
Approved based on reviews of depending PRs. 
See: https://github.com/BHoM/BHoMAnalytics_Toolkit/pull/35

2022-08-24 19:36 UTC, FraserGreenroyd commented
@BHoMBot check ready-to-merge

2022-08-24 19:38 UTC, merged