BHoM_UI: New boolean toggle component
BHoM/BHoM_UI pull request #472
Opened 2023-10-02 15:32 UTC by albinber

### NOTE: Depends on 

   
### Issues addressed by this PR

Closes #

### Test files

### Changelog

### Additional comments

2023-10-02 15:36 UTC, FraserGreenroyd requested changes

2023-10-02 15:36 UTC, FraserGreenroyd commented on BHoM_UI/Components/UI/FalseStartToggle.cs
> +        public override string Description { get; protected set; } = "A boolean toggle that changes to false on load.";
```suggestion
        public override string Description { get; protected set; } = "A boolean toggle that defaults to false on load.";
```

2023-10-02 15:36 UTC, FraserGreenroyd commented on BHoM_UI/Components/UI/FalseStartToggle.cs
> +        public override string Name { get; protected set; } = "FalseStart";
```suggestion
        public override string Name { get; protected set; } = "FalseStartToggle";
```

2023-10-02 15:36 UTC, FraserGreenroyd commented on BHoM_UI/Components/UI/FalseStartToggle.cs
> +            Name = "";
```suggestion
```

2023-10-02 15:36 UTC, FraserGreenroyd commented on BHoM_UI/Components/UI/FalseStartToggle.cs
> +
```suggestion
```

2023-10-03 14:32 UTC, FraserGreenroyd commented
@BHoMBot check versioning

2023-10-03 14:32 UTC, FraserGreenroyd commented
@BHoMBot check installer
@BHoMBot check core

2023-10-03 15:07 UTC, FraserGreenroyd approved these changes
![image](https://github.com/BHoM/BHoM_UI/assets/18049174/55183d25-e3a4-4f04-bf6d-cb3c54a474cb)

This looks great @albinber , great work and great team-work/collaboration on this.

I've reviewed the code and that looks fine.

I've tested in Grasshopper by setting a few components on the canvas, saving, and reopening the script and the components load in defaulting to `false`.

Happy to deploy to alphas.

2023-10-03 15:28 UTC, Tom-Kingstone approved these changes
![image](https://github.com/BHoM/BHoM_UI/assets/142492848/083532a1-fd2f-4b30-87e3-4765f333b1c1)
Tested on loading, and any toggles that were true are set to false, good job @albinber

2023-10-03 16:50 UTC, merged